image: registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

stages:
  - install
  - test

install:
  stage: install
  script:
    - echo "Limpiando cache"
    - npm cache clean --force
    - echo "Instalando dependencias"
    - npm ci --prefix src/main/frontend/packages/assembly-runner
    - echo "Verificando instalaci√≥n de vitest"
    - npm ls vitest --prefix src/main/frontend/packages/assembly-runner

test-assembly:
  stage: test
  script:
    - echo "Ejecutando pruebas asssembly"
    - cd src/main/frontend/packages/assembly-runner
    - npm test
  artifacts:
    when: always
    reports:
      junit: build/test-results/**/TEST-*.xml
    paths:
      - build/test-results/

